services:
  - type: web
    name: stucksupportbot
    env: python
    buildCommand: ""
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
